version: '2'
services:
    intersephipster-app:
        image: intersephipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://intersephipster-mysql:3306/intersephipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    intersephipster-mysql:
        extends:
            file: mysql.yml
            service: intersephipster-mysql
