version: '2'
services:
    intersep-app:
        image: intersep
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://intersep-postgresql:5432/intersep
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    intersep-postgresql:
        extends:
            file: postgresql.yml
            service: intersep-postgresql
